from enum import IntEnum


class InternalCodeEnum(IntEnum):
    SUCCESS = 0
    INVALID_PARAMS_ERROR = 10
    INVALID_AUTHENTICATION_ERROR = 20
    UNAUTHORIZED = 40
    DATA_VALIDATION_ERROR = 50
    DATA_NOT_FOUND = 51
    DATA_ALREADY_EXISTS = 52
    DATA_CONVERTER_ERROR = 53
    INFRASTRUCTURE_ERROR = 60
    INVALID_PROJECT_STATUS_ERROR = 70
    INVALID_USER_ID_ERROR = 71
    INTERNAL_SERVER_ERROR = 99
