from enum import IntEnum


class InternalCode(IntEnum):
    SUCCESS = 0
    INVALID_PARAMS_ERROR = 10
    INVALID_AUTHENTICATION_ERROR = 20
    INTERNAL_SERVER_ERROR = 30
    UNAUTHORIZED = 40
    DATA_VALIDATION_ERROR = 50
    DATA_NOT_FOUND = 51
    DATA_ALREADY_EXISTS = 52
    DATA_CONVERTER_ERROR = 53
    DATA_DECODER_ERROR = 54
    INFRASTRUCTURE_ERROR = 60
